### PR TITLE
Fix response of devices endpoint (Fixes #82)

### LINKED ISSUE #82: devices api endpoint returns html page
When requesting the /api/devices endpoint a html page is returned.

picture

### PR DESCRIPTION
**Pull request by pavelpilar**
Fixes #82 
Also removed an unused import I missed last time.

This fixes the issue of the *devices* endpoint sending an error when Spotify isn't authorized.

It does not fix the underlying issue of endpoint errors sending an HTML response, which the UI `fetch` function cannot parse as JSON, resulting in the exception described in #82. That should probably be changed to provide a more useful error message, instead of the current `Unexpected token < in JSON ...`.

### CODE REVIEW

**Comment by udoprog** [comment]
Thanks again!

Should the error be communicated to the frontend somehow? At the very least it feels like it should be logged.

**Comment by pavelpilar** [comment]
UI would now say 
```failed to request devices: Error: got bad status code: 500: {"code":500,"message":"Missing OAuth 2.0 Connection: Spotify"}```
instead of the original
```failed to request devices: SyntaxError: Unexpected token < in JSON at position 0```

File: bot/src/web/mod.rs [hunk 1]
```diff
@@ -831,7 +834,13 @@ impl Api {
...
 
         let c = player.current_device().await;
-        let data = player.list_devices().await?;
+        let data = match player.list_devices().await {
+            Ok(data) => data,
+            Err(_) => {
+                let data = Devices::default();
+                return Ok(warp::reply::json(&data));
+            }
+        };
```
Comment (udoprog) [inline bot/src/web/mod.rs:843]: Excellent job so far. What about this one?

If there is an error code which indicates an empty collection of devices, it should be handled in the client instead. Otherwise this swallows the error.

Alternatively, this seems like it can just fall through to the newfangled error handling you added :)

File: bot/src/web/mod.rs [hunk 2]
```diff
@@ -40,8 +40,11 @@ struct CustomReject(anyhow::Error);
 
 impl warp::reject::Reject for CustomReject {}
 
+// TODO: Also log which endpoint caused the error
 pub(crate) fn custom_reject(error: impl Into<anyhow::Error>) -> warp::Rejection {
-    warp::reject::custom(CustomReject(error.into()))
+    let error = error.into();
+    log::error!("Endpoint error caused by: {}", error);
```
Comment (udoprog) [inline bot/src/web/mod.rs:46]: Maybe log this in `recover` instead? Error handling is a bit messy in warp unfortunately and it would be nice to include endpoint.

File: bot/src/web/mod.rs (hunk 1 above)
Comment (pavelpilar) [reply bot/src/web/mod.rs:843]: Spotify API sends an empty array when no devices are available.
The `Devices` component currently handles 0 devices as either missing authorization or actually no devices.
https://github.com/udoprog/OxidizeBot/blob/91afe3148c70ac5bd56d8b1a32d04cc581ca28fb/bot-ui/src/components/Devices.js#L87-L93
It would be possible to split these two situations, sending the error when authorization is missing.

File: bot/src/web/mod.rs (hunk 2 above)
Comment (pavelpilar) [reply bot/src/web/mod.rs:46]: Unfortunately I haven't found anything in warp that would allow getting the endpoint path.
I will move the logging though as that is a better place for it anyway.

**Comment by udoprog** [comment]
Thanks a bunch! I'll cook a new release with this soon :)
